language: java
dist: xenial
jdk:
  - openjdk8
services:
  - elasticsearch
before_install:
  - chmod +x hbase-install.sh
before_script:
  - sleep 10
  - .travis/hbase-install.sh
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=nimbo3_DataPirates
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/downloads'
after_success:
  - bash <(curl -s https://codecov.io/bash)
addons:
  sonarcloud:
    organization: "nimbo3"
    token:
      secure: ${SONAR_TOKEN}
