language: java
dist: xenial
jdk:
  - openjdk8
services:
  - elasticsearch
before_install:
  - chmod +x .travis/hbase-install.sh
install: true
before_script:
  - .travis/hbase-install.sh
  - sleep 5
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=nimbo3_DataPirates
cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.sonar/cache'
addons:
  sonarcloud:
    organization: "nimbo3"
    token:
      secure: ${SONAR_TOKEN}
