language: java
jdk:
  - openjdk8
services:
  - elasticsearch
before_script:
  - .travis/hbase-install.sh
  - sleep 10
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=nimbo3_DataPirates
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
addons:
  sonarcloud:
    organization: "nimbo3"
    token:
      secure: ${SONAR_TOKEN}
